
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('recipes').del()
    .then(function () {
      // Inserts seed entries
      return knex('recipes').insert([
        {name: 'Meatless Lasagna', user_id: 1, ingredients: JSON.stringify([{"quantity": 20,"uom": "whole","ingredient": "lasagna noodles"}, {"quantity": 2,"uom": "tablespoon","ingredient": "olive oil"}, {"quantity": 3,"uom": "cups","ingredient": "tomato sauce"}, {"quantity": 1,"uom": "tablespoon","ingredient": "minced garlic"}, {"quantity": 1,"uom": "teaspoon","ingredient": "salt"}, {"quantity": 1,"uom": "teaspoon","ingredient": "dried oregano"}, {"quantity": 0.5,"uom":"teaspoon","ingredient":"ground pepper"}, {"quantity": 3,"uom": "cups","ingredient": "mozzarella cheese"}, {"quantity": 0.75,"uom": "cups","ingredient": "Romano cheese"}]), instructions: 'Preheat oven to 350 degrees F (175 degrees C). Bring a large pot of lightly salted water to a boil. Add lasagna noodles and cook for 8 to 10 minutes or until al dente, drain. In a skillet cook mushrooms, onions, and garlic in olive oil until tender. Drain excess liquid and cool. Combine ricotta cheese, Romano cheese, spinach, salt, oregano, basil, pepper, and egg in a bowl. Beat with an electric mixer on low speed for 1 minute. Lay 5 lasagna noodles in baking dish. Spread one third of the cheese/spinach mixture over noodles. Sprinkle 1 cup mozzarella cheese and 1/3 cup Parmesan cheese on top. Spread 1 cup pasta sauce over cheese. Repeat layering 2 times. Cover dish with aluminum foil and bake in a preheated oven for 1 hour. Cool 15 minutes before serving.', upvotes: 210, gluten_free: false, dairy_free: false, vegetarian: true, vegan: false, pescatarian: true, total_time: 40, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/3359675.jpg", blogpost_url: ''},

        {name: 'Meatless Meatballs', user_id: 1, ingredients: JSON.stringify([{"quantity": 1 , "uom": "tablespoon", "ingredient": "olive oil" },{"quantity": 1 , "uom": "pound", "ingredient": "chopped mushrooms" }, {"quantity": 1 , "uom": "pinch", "ingredient": "salt" },{"quantity": 1 , "uom": "tablespoon", "ingredient": "butter" },{"quantity": 0.5 , "uom": "cup", "ingredient": "finely chopped onion" },{"quantity": 2 , "uom": "cloves", "ingredient": "minced garlic"},{"quantity": 0.5 , "uom": "cup", "ingredient": "quick cooking oats" },{"quantity": 1 , "uom": "ounce", "ingredient": "parmigiano reggiano cheese" }]), instructions: 'Heat olive oil, mushrooms and salt, and stir until liquid from mushrooms has evaporated. Stir butter and onions into mushrooms and cook until golden brown. Mix oats add 1 ounce Parmigiano-Reggiano cheese into mixture. Preheat oven to 450 degrees F (230 degrees C). Form mixture into small meatballs using a 2-tablespoon scoop, arrange meatballs on prepared baking sheet. Bake in the preheated oven until meatballs are lightly golden brown, 12 to 15 minutes. Bring pasta sauce to a boil. Gently stir meatballs into sauce until coated. Simmer meatballs in sauce until cooked through, 45 minutes to 1 hour.', upvotes: 45, gluten_free: true, dairy_free: false, vegetarian: true, vegan: false, pescatarian: true, total_time: 28, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/2266615.jpg", blogpost_url: 'www.blogginallovadaworld.com/meatless'},

        {name: 'Salmon', user_id: 1, ingredients: JSON.stringify([{"quantity": 4 , "uom": "whole", "ingredient": "salmon fillets" },{"quantity": 1 , "uom": "tablespoon", "ingredient": "onion powder" }, {"quantity": 0.25 , "uom": "cup", "ingredient": "olive oil" },{"quantity": 4 , "uom": "cloves", "ingredient": "minced garlic" },{"quantity": 0.25 , "uom": "cup", "ingredient": "fresh lemon juice" },{"quantity": 2 , "uom": "tablespoons", "ingredient": "chopped green onions"}]), instructions: 'Season salmon fillets with lemon pepper, garlic powder, and salt.Preheat grill for medium heat. Lightly oil grill grate. Place salmon on the preheated grill, and discard marinade. Cook salmon for 6 to 8 minutes per side, or until the fish flakes easily with a fork.', upvotes: 107, gluten_free: true, dairy_free: true, vegetarian: false, vegan: false, pescatarian: true, total_time: 50, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/693200.jpg", blogpost_url: 'www.blogginallovadaworld.com/salmon'},

        {name: 'Baked Chicken with Apple Stuffing', user_id: 3, ingredients: JSON.stringify([{"quantity": 3 , "uom": "whole", "ingredient": "skinless chicken breast" },{"quantity": 3 , "uom": "whole", "ingredient": "chopped apples" }, {"quantity": 1 , "uom": "teaspoon", "ingredient": "olive oil" },{"quantity": 0.25 , "uom": "teaspoon", "ingredient": "dried thyme" },{"quantity": 2 , "uom": "pinch", "ingredient": "salt" }]), instructions: 'Preheat oven to 350 degrees F. Spray a baking dish with cooking spray and sprinkle with 1 pinch thyme. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/4-inch. Spread apples evenly over each chicken breast. Starting at one end, roll each breast around filling and secure the roll with a toothpick. Transfer breasts to prepared baking dish. Drizzle olive oil over each breast and sprinkle with remaining thyme. Cook chicken breasts until no longer pink in the center and the juices run clear, about 25 minutes. A thermometer inserted into the center of the meat should read at least 165 degrees F (74 degrees C).', upvotes: 132, gluten_free: true, dairy_free: true, vegetarian: false, vegan: false, pescatarian: false, total_time: 40, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/1055483.jpg", blogpost_url: ''},

        {name: 'Peachy Oatmeal', user_id: 4, ingredients: JSON.stringify([{"quantity": 15 , "uom": "oz", "ingredient": "sliced peaches" },{"quantity": 0.5 , "uom": "cup", "ingredient": "water" }, {"quantity": 0.5 , "uom": "cup", "ingredient": "milk" },{"quantity": 0.5 , "uom": "cup", "ingredient": "quick cooking oats" },{"quantity": 2 , "uom": "tablespoons", "ingredient": "brown sugar" },{"quantity": 1 , "uom": "pinch", "ingredient": "salt" }]), instructions: 'Stir peaches, water, milk, oats, brown sugar, cinnamon, and salt together in a microwave-safe bowl. Cook in microwave on High, stirring every 60 seconds, until the oats are softened, about 3 minutes. Stir one final time before serving.', upvotes: 67, gluten_free: true, dairy_free: false, vegetarian: true, vegan: false, pescatarian: true, total_time: 20, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/4052413.jpg", blogpost_url: ''},

        {name: 'GF Pepperoni Pizza', user_id: 5, ingredients: JSON.stringify([{"quantity": 3 , "uom": "tablespoon", "ingredient": "olive oil" },{"quantity": 1 , "uom": "cup", "ingredient": "chickpea flour" },{"quantity": 1 , "uom": "cup", "ingredient": "water" },{"quantity": 3 , "uom": "clove", "ingredient": "pressed garlic" },{"quantity": 0.5 , "uom": "teaspoon", "ingredient": "salt" }]), instructions: 'Preheat oven to 500 degrees F (260 degrees C).Coat the bottom and sides of a cast-iron skillet or an oven-proof baking dish with 1 tablespoon olive oil. Mix garbanzo bean flour and water together in a bowl until batter is smooth. Add remaining olive oil, garlic, and salt, mix well. Pour batter into the heated skillet. Cook crust in the preheated oven until lightly browned, about 15 minutes.', upvotes: 23, gluten_free: true, dairy_free: false, vegetarian: false, vegan: false, pescatarian: false, total_time: 45, recipe_pic_url: "http://images.media-allrecipes.com/userphotos/720x405/1341265.jpg", blogpost_url: ''},

        {name: 'Watermelon Salad', user_id: 7, ingredients: JSON.stringify([{"quantity": 4 , "uom": "cups", "ingredient": "watermelon" },{"quantity": 2, "uom": "tablespoons", "ingredient": "mint"},{"quantity": 1, "uom": "cup", "ingredient": "cucumber"},{"quantity": 1, "uom": "tablespoon", "ingredient": "olive oil"},{"quantity": 2, "uom": "tablespoons", "ingredient": "lime juice"}]), instructions: 'Chop watermelon into square, bite-sized pieces, and place into a bowl. Roughly chop mint leaves, then chop cucumber into thin pieces and add both to the bowl. Dress with olive oil and lime juice, mix until evenly coated.', upvotes: 43, gluten_free: true, dairy_free: true, vegetarian: true, vegan: true, pescatarian: true, total_time: 10, recipe_pic_url: "http://res.cloudinary.com/dcc5vb7ot/image/upload/v1508515068/Watermelon-Salad-with-Feta-and-Cucumber-5_jebiub.jpg", blogpost_url: ''},

        {name: 'Braised Balsamic Chicken', user_id: 7, ingredients: JSON.stringify([{"quantity": 6, "uom": "pounds", "ingredient": "skinless, boneless chicken breast halves"},{"quantity": 1, "uom": "tablespoon", "ingredient": "minced garlic"},{"quantity": 2, "uom": "tablespoons", "ingredient": "olive oil"},{"quantity": 1, "uom": "cup", "ingredient": "sliced onion"},{"quantity": 14.5, "uom": "ounces" , "ingredient": "canned diced tomatoes"},{"quantity": 0.5, "uom": "cups", "ingredient": "balsamic vinegar"},{"quantity": 1, "uom": "teaspoon", "ingredient": "dried oregano"},{"quantity": 1, "uom": "teaspoon", "ingredient": "dried rosemary"},{"quantity": 0.5, "uom": "teaspoon", "ingredient": "dried thyme"}]), instructions:'Heat oil in a pan, then add chicken breasts once the oil is hot. Cook until browned, add salt and pepper to taste. Add onion and cook until tender and slightly browned. Pour tomatoes and vinegar into the pan, then add the dried herbs. Simmer until the chicken is not pink and its internal temperature is 170 degrees F.', upvotes: 61, gluten_free: true, dairy_free: true, vegetarian: false, vegan: false, pescatarian: false, total_time: 60, recipe_pic_url: "https://static.pexels.com/photos/291767/pexels-photo-291767.jpeg", blogpost_url: ''},

        {name: 'Tofu Tacos', user_id: 9, ingredients: JSON.stringify([{"quantity": 12 , "uom": "ounces", "ingredient": "firm tofu"},{"quantity": 4 , "uom": "cups", "ingredient": "shredded coleslaw mix"},{"quantity": 1 , "uom": "cup", "ingredient": "diced radishes"},{"quantity": 0.5 , "uom": "cups", "ingredient": "cilantro"},{"quantity": 1 , "uom": "cup", "ingredient": "sliced scallions"},{"quantity": 1.5 , "uom": "tablespoon", "ingredient": "olive oil"},{"quantity": 2 , "uom": "whole", "ingredient": "limes"},{"quantity": 0.25 , "uom": "cups", "ingredient": "greek yogurt"},{"quantity": 1 , "uom": "tablespoon", "ingredient": "taco seasoning"},{"quantity": 8 , "uom": "whole", "ingredient": "corn tortillas"},{"quantity": 0.25 , "uom": "cups", "ingredient": "shredded cheese"},{"quantity": 0.25 , "uom": "cups", "ingredient": "salsa verde"}]), instructions: 'Press the tofu for 10 minutes to remove moisture. Mix the coleslaw, radishes, cilantro, scallions, half the olive oil, and the juice and zest of one of the limes in a large bowl. In a smaller bowl, mix the yogurt and juice of the remaining lime into a sauce, season to taste with salt and pepper. Brush the tofu with the remaining oil once it is done draining, and sprinkle on taco seasoning. Add the tofu to a hot, nonstick pan and cook until crisp, then flip and crisp the other side. Cut into strips. Warm the tortillas, then fill with tofu, cheese, and the slaw mixture. Add the salsa and yogurt sauce prior to serving.',upvotes: 529, gluten_free: true, dairy_free: true, vegetarian: true, vegan: true, pescatarian: true, total_time: 40, recipe_pic_url: "http://res.cloudinary.com/dcc5vb7ot/image/upload/v1508514932/tofutacos_dyl4xx.jpg", blogpost_url: ''},

        {name: 'Southwestern Salad', user_id: 10, ingredients: JSON.stringify([{"quantity": 0.5, "uom": "whole", "ingredient": "avocado"},{"quantity": 0.75, "uom": "cups", "ingredient": "yogurt"},{"quantity": 2, "uom": "whole", "ingredient": "scallions"},{"quantity": 1, "uom": "clove", "ingredient": "garlic"},{"quantity": 1, "uom": "tablespoon", "ingredient": "lime juice"},{"quantity": 0.5, "uom": "teaspoon", "ingredient": "sugar"},{"quantity": 3, "uom": "cups", "ingredient": "mixed greens"},{"quantity": 0.5, "uom": "cups", "ingredient": "canned black beans"},{"quantity": 0.5, "uom": "cups", "ingredient": "corn"},{"quantity": 0.5, "uom": "cups", "ingredient": "cherry tomatoes"}]), instructions: 'Blend avocado, cilantro, yogurt, scallions, garlic, lime juice, and sugar until a smooth sauce. Toss the greens in a large salad bowl with the dressing, black beans, corn, and tomatoes.', upvotes: 2, gluten_free: true, dairy_free: false, vegetarian: true, vegan: false, pescatarian: true, total_time: 35, recipe_pic_url: "https://static.pexels.com/photos/291767/pexels-photo-291767.jpeg", blogpost_url: 'www.blogginallovadaworld.com/swchick'},
      ]);
    });
};
